Filter out null keywords.
canonical/appstream.dart pull request #23
Opened 2022-11-16 22:22 UTC by oSoMoN

Fixes #22.

2022-11-16 22:48 UTC, robert-ancell requested changes
Can you add a test for this?

2022-11-16 23:01 UTC, oSoMoN commented
Done. This is what the output of `flutter test` looks like when the fix is reverted in this branch:

    00:01 +30 -1: collection - keywords (null values) - yaml [E]                                                                                         
      type 'Null' is not a subtype of type '_Mismatch' in type cast
      package:matcher/src/equals_matcher.dart 272:43  _DeepMatcher.describeMismatch
      package:test_api                                expect
      test/appstream_test.dart 766:5                  main.<fn>

2022-11-17 00:04 UTC, robert-ancell commented
Thanks!

2022-11-17 00:04 UTC, robert-ancell approved these changes

2022-11-17 00:04 UTC, merged